# Site settings
title: Vivian Zhao
description: Vivian Zhao's Personal Website
keywords: Art, Calligraphy, Music
author: Vivian Zhao
baseurl: "" # the subpath of your site, e.g. /blog/
url: "vivianzhao9.github.io" # the base hostname & protocol for your site
paginate: 3
google_analytics: 'UA-XXXXXXX-X'

github: [metadata]
