# Site settings
title: Vivian Zhao
description: Modern-Blog A Elegant template for Jekyll
keywords: Art, Calligraphy, Music
author: Vivian Zhao
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
gems: [jekyll-paginate,jekyll-seo-tag,jekyll-sitemap]
paginate: 3
google_analytics: 'UA-XXXXXXX-X'
